[package]
name = "f-structs-traits"
version = "0.1.0"
authors = ["JonTDean <JonathanTomDean@Gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
